media:
  input: _src/static/media
  output: media
content:
  - name: "settings"
    label: "Website Settings"
    path: "_src/_data/site.yml"
    type: file
    fields:
      - { name: "name", label: "Naam", type: "string" }
      - { name: "logo", label: "Logo", type: "image" }

  - name: "homepage"
    label: "Home page"
    path: "content/_index.md"
    type: file
    fields:
      - { name: title, label: "Pagina title", type: "string" }
      - { name: description, label: "Pagina beschrijving", type: "string" }

      - name: "metas"
        label: "metas"
        type: "object"
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "description", label: "Description", type: "string" }

  - name: "hero"
    label: "Hero Section"
    path: "data/home/hero.yml"
    type: file
    fields:
      - { name: "intro", label: "Intro", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - name: "image"
        label: "Image"
        widget: "object"
        fields:
          - { name: "url", label: "URL", widget: "image" }
          - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "video_id", label: "Video id", widget: "string" }


  - name: "spotify"
    label: "Spotify Section"
    path: "data/home/spotify.yml"
    type: file
    fields:
      - { name: "intro", label: "Intro", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - name: "spotify"
        label: "Spotify"
        widget: "object"
        fields:
          - { name: "type", label: "Type", widget: "select", options: ["album", "track", "artist"] }
          - { name: "id", label: "ID", widget: "string" }